### ISSUE TITLE
Error with pelican-minification

### ISSUE THREAD

**Issue by abr4xas** [dArignac/pelican-minification#2]
Hi there, 
```html
<html lang=en><head><meta charset=utf-8><title>
...
```
this plugin remove all quotes :(

**Comment by dArignac** [comment]
Confirmed. I'll have a look into this.

**Comment by abr4xas** [comment]
Thx :)

**Comment by dArignac** [comment]
I built a new version, find it on PyPI: https://pypi.python.org/pypi/pelican-minification
Please test if it works for you now, thanks!

**Comment by abr4xas** [comment]
Hi!
Thanks, it's works :D
